### ISSUE TITLE
Solved: Does not compile on ubuntu 18.04

### ISSUE THREAD

**Issue by mark-orion** [iurie-sw/geonkick#119]
Is there any workaround for this ?

In file included from /home/mark/apps/src/geonkick/utils/base64.h:12:0,
                 from /home/mark/apps/src/geonkick/utils/base64.cpp:10:
/home/mark/apps/src/geonkick/src/globals.h:37:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/geonkick_common.dir/build.make:722: recipe for target 'CMakeFiles/geonkick_common.dir/utils/base64.cpp.o' failed
make[2]: *** [CMakeFiles/geonkick_common.dir/utils/base64.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/geonkick_common.dir/all' failed
make[1]: *** [CMakeFiles/geonkick_common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iurienistor** [comment]
The best solution is to update the compiler version that supports filesystem.
A workaround is in globals.h to change

#include <filesyistem>

with

#include <experimental/filesystem>
#define filesystem experimental::filesystem

**Comment by mark-orion** [comment]
That worked. Thanks for the quick help - and last but not least this great drum synth....
